---
target_dir: '/mnt'

mkinitcpio_files:
  - /root/cryptlvm.keyfile
mkinitcpio_hooks:
  - base
  - udev
  - autodetect
  - modconf
  - block
  - encrypt
  - lvm2
  - filesystems
  - keyboard
  - fsck

grub_cmdline_linux: cryptdevice=/dev/disk/by-partlabel/Primary:cryptlvm cryptkey=rootfs:/root/cryptlvm.keyfile
grub_enable_cryptodisk: y
