---
# tasks file for btrfs

- name: Ensure BTRFS tools are installed
  pacman:
    name: btrfs-progs

- name: Create temporary mountpoints
  tempfile:
    state: directory
    prefix: btrfs_
  with_items: '{{ btrfs_volumes }}'
  register: _btrfs_tmpdirs

- name: Mounting BTRFS devices to temporary mountpoint
  mount:
    src: "{{ item.item }}"
    path: "{{ item.path }}"
    fstype: btrfs
    opts: subvol=/
    state: mounted
  with_items: '{{ _btrfs_tmpdirs.results }}'
  loop_control:
    label: '{{ item.item }}'

- name: Create BTRFS subvolumes on each device
  include_tasks: subvolumes.yml
  with_items: '{{ _btrfs_tmpdirs.results }}'
  loop_control:
    loop_var: _btrfs_mountpoint

- name: Set default BTRFS subvolume
  command: >
    btrfs subvolume
      set-default '{{ item.path }}/{{ btrfs_volumes[item.item].default }}'
  when: '"default" in btrfs_volumes[item.item]'
  with_items: '{{ _btrfs_tmpdirs.results }}'

- name: Unmounting BTRFS devices to temporary mountpoint
  mount:
    src: "{{ item.item }}"
    path: "{{ item.path }}"
    state: unmounted
  with_items: '{{ _btrfs_tmpdirs.results }}'
  loop_control:
    label: '{{ item.item }}'
