---
# tasks file for systemd-boot

- name: Install systemd-boot
  command: 'bootctl --path={{ systemd_boot_esp }} install'

- name: Stat root device
  stat:
    path: '{{ _systemd_boot_device }}'
  register: _systemd_boot_device_stat

- name: Get root device PARTUUID
  command: >
    blkid {{ _systemd_boot_device }}
    --match-tag PARTUUID --output value
  changed_when: false
  check_mode: false
  register: _systemd_boot_partuuid

- name: Create boot entry
  template:
    src: arch.conf.j2
    dest: '{{ systemd_boot_entry }}'

- name: Configure default entrie
  copy:
    content: |
      default arch
    dest: '{{ systemd_boot_esp }}/loader/loader.conf'

- name: Install Intel microcode
  pacman:
    name: intel-ucode
  when: &intel 'ansible_processor | map("search", "Intel")'

- name: Add Intel microcode entry
  lineinfile:
    path: '{{ systemd_boot_entry }}'
    regexp: 'initrd\s+/intel-ucode\.img'
    insertafter: '^linux '
    line: 'initrd  /intel-ucode.img'
  when: *intel
