---
# handlers file for grub

- name: Install GRUB
  command: >
    grub-install
      --target '{{ grub_target }}'
      --efi-directory '{{ grub_efi_directory }}'
      --bootloader-id '{{ grub_bootloader_id }}'
      --removable
      --recheck

- name: Generate GRUB configuration
  command: grub-mkconfig
  register: _grub_config
  changed_when: false
  check_mode: false
  listen: Configure GRUB

- name: Write GRUB configuration
  copy:
    content: '{{ _grub_config.stdout }}'
    dest: '{{ grub_config_path }}'
  listen: Configure GRUB
