repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.7
  hooks:
    - id: ansible-lint
- repo: local
  hooks:
    - id: packer-fmt
      name: packer-fmt
      description: Rewrites all Packer configuration files to a canonical format.
      entry: sh -c 'for f in "${@}"; do packer fmt "${f}"; done' --
      language: system
      files: '^.*\.pkr(?:vars)?\.hcl$'
