---
- hosts: all
  roles:
    - role: mount
    - role: mirrorlist
    - role: bootloader/systemd-boot
    - role: locales
    - role: network/connman
    - name: VirtualBox hardware
      role: hardware/virtualbox
      when: ansible_product_name == "VirtualBox"
    - role: vagrant
    - role: mkinitcpio
