collections:
- name: ansible.posix
  version: 1.1.1
- name: community.general
  version: 1.3.5

roles:
- name: maxbrunet.btrfs-subvolume
  src: https://github.com/maxbrunet/ansible-btrfs-subvolume
  version: 4cfea60ac2efd2178a7a6d65afc57ff9822e4fe9
