---
# tasks file for virtualbox

# VirtualBox Guest Additions
# https://wiki.archlinux.org/index.php/VirtualBox
- name: Install VirtualBox Guest Additions
  pacman:
    name: '{{ item }}'
  with_items:
    - linux-headers
    - virtualbox-guest-utils
    - virtualbox-guest-modules-arch
    - nfs-utils

- name: Load VB Guest kernel modules
  copy:
    content:
      vboxguest
      vboxsf
      vboxvideo
    dest: /etc/modules-load.d/virtualbox.conf

- name: Enable VB guest services
  service:
    name: '{{ item }}'
    enabled: true
  with_items:
    - vboxservice.service
    - rpcbind.service

- name: Add groups for VirtualBox folder sharing
  user:
    name: vagrant
    groups: vboxsf
    append: true

- name: Create zero file
  tempfile:
    path: /
    prefix: zerofile.
    state: file
  register: _zerofile

- name: Write zero to improve virtual disk compaction
  command: '/usr/bin/dd if=/dev/zero of="{{ _zerofile.path }}" bs=1M conv=sync'
  register: _writezero 
  failed_when:
    - '"No space left on device" not in _writezero.stderr'
    - writezero.failed

- name: Remove zero file
  file:
    path: '{{ _zerofile.path }}'
    state: absent
