---
# tasks file for virtualbox

# VirtualBox Guest Additions
# https://wiki.archlinux.org/index.php/VirtualBox
- name: Install VirtualBox Guest Additions
  pacman:
    name: '{{ item }}'
  with_items:
    - linux-headers
    - virtualbox-guest-utils
    - virtualbox-guest-modules-arch
    - nfs-utils

- name: Load VB Guest kernel modules
  copy:
    content:
      vboxguest
      vboxsf
      vboxvideo
    dest: /etc/modules-load.d/virtualbox.conf

- name: Enable VB guest services
  service:
    name: '{{ item }}'
    enabled: true
  with_items:
    - vboxservice.service
    - rpcbind.service
