---
# tasks file for systemd_boot

- name: Install systemd-boot
  command: 'bootctl --path={{ systemd_boot_esp }} install' # noqa 301

- name: Create boot entry
  template:
    src: arch.conf.j2
    dest: '{{ systemd_boot_entry }}'
    mode: '0600'

- name: Configure default entry
  copy:
    content: |
      default arch
    dest: '{{ systemd_boot_esp }}/loader/loader.conf'
    mode: '0600'

- name: Install Intel microcode
  pacman:
    name: intel-ucode
  when: &intel 'ansible_processor | map("search", "Intel")'

- name: Add Intel microcode entry
  lineinfile:
    path: '{{ systemd_boot_entry }}'
    regexp: 'initrd\s+/intel-ucode\.img'
    insertafter: '^linux '
    line: 'initrd  /intel-ucode.img'
  when: *intel
