---
# tasks file for mount

- name: Ensure filesystems utilities are installed
  pacman:
    name: '{{ item.packages }}'
  when: item.fstype in mount_list | map(attribute="fstype")
  with_items: '{{ _mount_fsprogs }}'
  loop_control:
    label: '{{ item.packages }}'

- name: Mounting partitions to mountpoint directory
  mount:
    src: "{{ item.src }}"
    path: "{{ mount_base_mountpoint }}{{ item.mountpoint }}"
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  with_items:
    '{{ mount_list | sort(attribute="mountpoint") }}'
  loop_control:
    label: '{{ item.src }}'
