---
# tasks file for mount

- name: Mounting partitions to mountpoint directory
  mount:
    src: "{{ item.src }}"
    path: "{{ mount_base_mountpoint }}{{ item.mountpoint }}"
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  with_items:
    '{{ mount_list | sort(attribute="mountpoint") }}'
  loop_control:
    label: '{{ item.src }}'
