---
# tasks file for vagrant
- name: Install sshd
  pacman:
    name: openssh

- name: Enable sshd
  service:
    name: sshd
    enabled: true

# Vagrant-specific configuration
- name: Configure sudo for vagrant user
  copy:
    content: |
      Defaults env_keep += "SSH_AUTH_SOCK"
      vagrant ALL=(ALL) NOPASSWD: ALL
    dest: /etc/sudoers.d/10_vagrant
    mode: 0440
    validate: /usr/sbin/visudo -cf %s

- name: Add vagrant pub SSH key
  authorized_key:
    user: vagrant
    state: present
    key: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
