---
# vars file for systemd-boot

# uuid is not always available in ansible_mounts
# but we can still find it in ansible_device_links
_systemd_boot_mount_query: "[?mount == '{{ syslinux_root_mount }}'] | [0]"
# Need to stat the device to know if it's a link to a device mapper
_systemd_boot_mount:
  '{{ ansible_mounts | json_query(_systemd_boot_mount_query) }}'
_systemd_boot_device: '{{ _systemd_boot_mount.device }}'
_systemd_boot_fstype: '{{ _systemd_boot_mount.fstype }}'
_systemd_boot_real_device:
  '{%- if _systemd_boot_device_stat.stat.islnk -%}
     {{ _systemd_boot_device_stat.stat.lnk_source }}
   {%- else -%}
     {{ _systemd_boot_device_stat.stat.path }}
   {%- endif -%}'
