---
# defautls file for connman
connman_conf_path: /etc/connman/main.conf
connman_conf:
  - section: General
    settings:
      # https://wiki.archlinux.org/index.php/ConnMan#Avoid_changing_the_hostname
      - option: AllowHostnameUpdates
        value: false
      # https://wiki.archlinux.org/index.php/ConnMan#Prefer_ethernet_to_wireless
      - option: PreferredTechnologies
        value: ethernet,wifi
      # https://wiki.archlinux.org/index.php/ConnMan#Blacklist_interfaces
      - option: NetworkInterfaceBlacklist
        value: vmnet,vboxnet,virbr,ifb,docker,veth,eth,wlan
