---
# tasks file for mkinitcpio

- name: Install hooks dependencies
  pacman:
    name: '{{ item.packages }}'
  when: item.hook in mkinitcpio_hooks
  with_items: '{{ _mkinitcpio_hookdeps }}'

- name: Create mkinitcpio config
  template:
    src: mkinitcpio.conf.j2
    dest: '{{ mkinitcpio_conf }}'
  notify:
    - Refresh initramfs image

- name: Create initramfs image
  command: '{{ mkinitcpio_command }}'
  args:
    creates: '{{ mkinitcpio_image }}'
