---
# tasks file for mount

- tags: mount
  block:

    - name: Mounting partitions to mountpoint directory
      mount:
        backup: '{{ item.backup | default(omit) }}'
        dump: '{{ item.dump | default(omit) }}'
        fstype: '{{ item.fstype | default(omit)}}'
        opts: '{{ item.opts | default(omit) }}'
        passno: '{{ item.passno | default(omit) }}'
        src: "{{ item.src | default(omit) }}"
        path: "{{ _mount_path }}"
        state: '{{ item.state | default("mounted") }}'
      with_items: '{{ mount_volumes | sort(attribute="path") }}'
      loop_control:
        label: '{{ item.path }}'

    - name: Set mountpoint directory permissions
      file:
        path: '{{ _mount_path }}'
        state: directory
        owner: '{{ item.mount_owner | default(omit) }}'
        group: '{{ item.mount_group | default(omit) }}'
        mode: '{{ item.mount_mode | default(omit) }}'
      when: item.state | default('mounted') == 'mounted'
      with_items: '{{ mount_volumes }}'
      loop_control:
        label: '{{ item.path }}'

    - name: Check if swap partitions are active
      command: swaplabel '{{ volume.src }}'
      failed_when: false
      changed_when: false
      check_mode: false
      register: _mount_swap
      with_items: '{{
        mount_volumes | selectattr("fstype", "eq", "swap") | list
      }}'
      loop_control:
        loop_var: volume
        label: '{{ volume.src }}'

    - name: Enable added swap partitions
      command: swapon '{{ item.volume.src }}'
      when:
        - item.rc != 0
        - item.volume.state == "present"
      with_items: '{{ _mount_swap.results }}'
      loop_control:
        label: '{{ item.volume.src }}'

    - name: Disable removed swap partitions
      command: swapoff '{{ item.volume.src }}'
      when:
        - item.rc == 0
        - item.volume.state in ["unmounted", "absent"]
      with_items: '{{ _mount_swap.results }}'
      loop_control:
        label: '{{ item.volume.src }}'
