---
# tasks file for vagrant
- name: Generate password
  command: openssl passwd -crypt 'vagrant'
  register: _vagrant_password
  when: _vagrant_password is not defined

- name: Install sshd
  pacman:
    name: openssh

- name: Disable sshd client reverse dns lookup
  replace:
    path: /etc/ssh/sshd_config
    regexp: '#UseDNS yes'
    replace: 'UseDNS no'

- name: Enable sshd
  service:
    name: sshd
    enabled: true

# Vagrant-specific configuration
- name: Create vagrant user
  user:
    name: vagrant
    password: '{{ _vagrant_password.stdout }}'
    comment: 'Vagrant User'

- name: Configure sudo for vagrant user
  copy:
    content: |
      Defaults env_keep += "SSH_AUTH_SOCK"
      vagrant ALL=(ALL) NOPASSWD: ALL
    dest: /etc/sudoers.d/10_vagrant
    mode: 0440
    validate: /usr/sbin/visudo -cf %s

- name: Add vagrant pub SSH key
  authorized_key:
    user: vagrant
    state: present
    key: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
