---
# tasks file for arch-chroot

- name: Mount api filesystems
  mount:
    src: '{{ item.src }}'
    path: '{{ chroot_dir }}{{ item.path }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  with_items: '{{ _chroot_mnt }}'
  loop_control:
    label: '{{ item.path }}'

- name: Stat maybe mounts
  stat:
    path: '{{ item.path }}'
  register: _chroot_stat
  with_items: '{{ _chroot_maybe_mnt }}'
  loop_control:
    label: '{{ item.path }}'

- name: Maybe mount filesystems
  mount:
    src: '{{ item.src }}'
    path: '{{ chroot_dir }}{{ item.path }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  when: '{{ (
    _chroot_stat.results | selectattr("item.path", "eq", item.path) | first
  ).stat.exists }}'
  with_items: '{{ _chroot_maybe_mnt }}'
  loop_control:
    label: '{{ item.path }}'

- name: Install python in chroot
  command: >
    pacman -S python --noconfirm
      --root {{ chroot_dir }}
      --cachedir {{ chroot_dir }}/var/cache/pacman/pkg
