---
# tasks file for mirrorlist

- name: Install Reflector
  pacman:
    name: reflector

- name: Generate MirrorList
  command: >
    reflector
      --latest 5
      --country {{ mirrorlist_country }}
      --protocol https
      --sort rate
  register: _mirrorlist_reflector
  changed_when: false
  check_mode: false

# Allows to use Ansible `--diff` option
# to see mirrorlist changes
- name: Install Optimized MirrorList
  copy:
    content: |
      {{ _mirrorlist_reflector.stdout }}
    dest: '{{ _mirrorlist_path }}'
