---
# tasks file for arch-chroot

- name: Mount api filesystems
  mount:
    src: '{{ item.src }}'
    path: '{{ chroot_dir }}{{ item.path }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  with_items: '{{ _chroot_mnt }}'
  loop_control:
    label: '{{ item.path }}'

- name: Stat target /sys/firmware/efi/efivars
  stat:
    path: '{{ chroot_dir }}/sys/firmware/efi/efivars'
  register: efivars_file

- name: Maybe mount filesystems
  mount:
    src: '{{ item.src }}'
    path: '{{ chroot_dir }}{{ item.path }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  when: item.when
  with_items: '{{ _chroot_maybe_mnt }}'
  loop_control:
    label: '{{ item.path }}'

- name: Mount resolv.conf
  mount:
    src: '{{ item.src }}'
    path: '{{ chroot_dir }}{{ item.path }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  with_items: '{{ _chroot_mnt_resolvconf }}'
  loop_control:
    label: '{{ item.path }}'

- name: Install python in chroot
  command: >
    pacman -S python --noconfirm
      --root {{ chroot_dir }}
      --cachedir {{ chroot_dir }}/var/cache/pacman/pkg
