---
# defaults file for mount
mount_base_mountpoint: ''

mount_list:
  - src: PARTLABEL=EFI
    mountpoint: /boot
    fstype: vfat
    opts: defaults
  - src: PARTLABEL=System
    mountpoint: /
    fstype: ext4
    opts: defaults
