---
# vars file for partition
_partition_dev: '{{ item.device }}{{ item.number }}'

_partition_fsprogs:
  - fstype: btrfs
    packages: btrfs-progs
  - fstype: ext2
    packages: e2fsprogs
  - fstype: ext3
    packages: e2fsprogs
  - fstype: ext4
    packages: e2fsprogs
  - fstype: f2fs
    packages: f2fs-tools
  - fstype: lvm
    packages: lvm2
  - fstype: reiserfs
    packages: reiserfsprogs
  - fstype: swap
    packages: util-linux
  - fstype: vfat
    packages: dosfstools
  - fstype: xfs
    packages: xfsprogs
