---
# tasks file for partition
- name: Clearing partition table on disk
  command: '/usr/bin/sgdisk --zap {{ partition_device }}'
  when: &new_disk |
    ansible_devices[( partition_device | basename )].partitions == {} or
    partition_reset

- name: Destroying magic strings and signatures on disk (1)
  command: '/usr/bin/dd if=/dev/zero of={{ partition_device }} bs=512 count=2048'
  when: *new_disk

- name: Destroying magic strings and signatures on disk (2)
  command: '/usr/bin/wipefs --all {{ partition_device }}'
  when: *new_disk

- name: Creating /root partition on disk
  command: '/usr/bin/sgdisk --new=1:0:0 {{ partition_device }}'
  when: *new_disk

- name: Setting disk bootable
  command: '/usr/bin/sgdisk {{ partition_device }} --attributes=1:set:2'
  when: *new_disk

- name: Creating /root filesystem (ext4)
  command: '/usr/bin/mkfs.ext4 -O ^64bit -F -m 0 -q -L root {{ partition_id }}'
  when: *new_disk

- name: Mounting root partion to target dir
  mount:
    src: "{{ partition_id }}"
    path: "{{ partition_mountpoint }}"
    fstype: ext4
    opts: noatime,errors=remount-ro
    state: mounted

- name: Ensure etc directory exits
  file:
    path: '{{ partition_mountpoint }}/etc'
    state: directory

- name: Generate the filesystem table
  command: '/usr/bin/genfstab -p -t UUID {{ partition_mountpoint }}'
  register: _partition_genfstab
  changed_when: false
  check_mode: false

- name: Write the filesystem table
  copy:
    content: |
      {{ _partition_genfstab.stdout }}
    dest: '{{ partition_mountpoint }}/etc/fstab'
