---
# tasks file for partition
- name: Remove all partitions from disk
  parted:
    device: '{{ partition_device }}'
    number: '{{ partition_device | regex_search("^.*?(\d+)$") }}'
    stage: absent
  when: partition_reset
  with_items:
    '{{ ansible_devices[( partition_device | basename )].partitions }}'

- name: Create partitions
  parted:
    name: '{{ item.name | default() }}'
    device: '{{ item.device }}'
    number: '{{ item.number }}'
    flags: '{{ item.flags | default([]) }}'
    part_start: '{{ item.part_start }}'
    part_end: '{{ item.part_end }}'
    label: '{{ partition_label }}'
    state: present
  with_items: '{{ partition_list }}'
  loop_control:
    label: '{{ _partition_dev }}'

- name: Create filesystems
  filesystem:
    fstype: '{{ item.fstype }}'
    dev: '{{ _partition_dev }}'
  with_items: '{{ partition_list }}'
  loop_control:
    label: '{{ _partition_dev }}'
