---
- hosts: all
  pre_tasks:
    - name: Create initramfs CPIO image
      command: /usr/bin/mkinitcpio -p linux
      #args:
      #  creates: /boot/initramfs-linux.img
  roles:
    - role: mirrorlist
    - role: bootloader/systemd-boot
    - role: locales
    - role: network
    - name: VirtualBox hardware
      role: hardware/virtualbox
      when: ansible_product_name == "VirtualBox"
    - role: vagrant
