---
- hosts: all
  tasks:
    - name: Clean the pacman cache.
      command: '{{ item }}'
      with_items:
        - /usr/bin/pacman -Scc --noconfirm
        - /usr/bin/pacman-optimize

    - name: Create zero file
      tempfile:
        path: /
        prefix: zerofile.
        state: file
      register: _zerofile

    - name: Write zero to improve virtual disk compaction
      command: '/usr/bin/dd if=/dev/zero of="{{ _zerofile.path }}" bs=1M conv=sync'
      register: _writezero
      failed_when:
        - '"No space left on device" not in _writezero.stderr'
        - writezero.failed

    - name: Remove zero file
      file:
        path: '{{ _zerofile.path }}'
        state: absent
