---

- name: '{{ volume.vg }} - Create logical volumes'
  lvol:
    vg: '{{ volume.vg }}'
    lv: '{{ item.lv }}'
    size: '{{ item.size }}'
  with_items: '{{ volume.lvs }}'
  loop_control:
    label: '{{ item.lv }}'

- name: '{{ volume.vg }} - Create filesystems'
  filesystem:
    fstype: '{{ item.fstype }}'
    dev: '/dev/{{ volume.vg }}/{{ item.lv }}'
  with_items: '{{ volume.lvs }}'
  loop_control:
    label: '{{ item.lv }}'
