---
- name: Check if swap filesystem exists
  command: 'swaplabel "/dev/{{ item.vg }}/{{ item.lv }}"'
  register: _lvm_swap
  changed_when: false
  failed_when: false
  check_mode: false

- name: Create swap filesystem
  command: 'mkswap "/dev/{{ item.vg }}/{{ item.lv }}"'
  when: _lvm_swap.rc != 0
