---
- name: '/dev/{{ volume.vg }}/{{ item.lv }} - Check if swap filesystem exists'
  command: 'swaplabel "/dev/{{ volume.vg }}/{{ item.lv }}"'
  register: _lvm_swap
  changed_when: false
  failed_when: false
  check_mode: false

- name: '/dev/{{ volume.vg }}/{{ item.lv }} - Create swap filesystem'
  command: 'mkswap "/dev/{{ volume.vg }}/{{ item.lv }}"'
  when: _lvm_swap.rc != 0
